name: pix
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anyio=4.12.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h9408147_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.2.0=py311h97d6d38_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py311hdc60ec4_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cctools_impl_osx-arm64=1030.6.3=llvm19_1_h8c76c84_1
  - cctools_osx-arm64=1030.6.3=llvm19_1_h6d92914_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311hd10dc20_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - clang=19.1.7=default_hf9bcbb7_5
  - clang-19=19.1.7=default_h73dfc95_5
  - clang_impl_osx-arm64=19.1.7=h76e6a08_27
  - clang_osx-arm64=19.1.7=h07b0088_27
  - clangxx=19.1.7=default_h36137df_5
  - clangxx_impl_osx-arm64=19.1.7=h276745f_27
  - clangxx_osx-arm64=19.1.7=h07b0088_27
  - comm=0.2.3=pyhe01879c_0
  - compiler-rt=19.1.7=h855ad52_1
  - compiler-rt_osx-arm64=19.1.7=he32a8d3_1
  - cpython=3.11.14=py311hd8ed1ab_2
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.17=py311hc58e375_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - eigen=3.4.0=h49c215f_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fenics=2019.1.0=h46ec8c0_61
  - fenics-dijitso=2019.1.0=pyhd8ed1ab_39
  - fenics-dolfin=2019.1.0=py311hac4b950_61
  - fenics-ffc=2019.1.0=pyhd8ed1ab_40
  - fenics-fiat=2019.1.0=pyhd8ed1ab_40
  - fenics-libdolfin=2019.1.0=h30c91c4_61
  - fenics-ufl=2019.1.0=pyhd8ed1ab_16
  - fftw=3.3.10=mpi_mpich_h6eb47b5_11
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py311hd340a2e_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hdf5=1.14.6=mpi_mpich_h7e00a95_4
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hypre=2.32.0=mpi_mpich_h189fe77_1
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h7eeda09_0
  - ld64_osx-arm64=956.6=llvm19_1_h6922315_1
  - lerc=4.0.0=hd64df32_1
  - libaec=1.1.4=h51d1e36_0
  - libamd=3.3.3=h5087772_7100102
  - libblas=3.11.0=4_h51639a9_openblas
  - libboost=1.88.0=h18cd856_6
  - libboost-headers=1.90.0=hce30654_0
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libbtf=2.3.2=h99b4a89_7100102
  - libcamd=3.3.3=h99b4a89_7100102
  - libcblas=3.11.0=4_hb0561ab_openblas
  - libccolamd=3.3.4=h99b4a89_7100102
  - libcholmod=5.3.1=hbba04d7_7100102
  - libclang-cpp19.1=19.1.7=default_h73dfc95_5
  - libcolamd=3.3.4=h99b4a89_7100102
  - libcurl=8.17.0=hdece5d2_1
  - libcxsparse=4.4.1=h9e79f82_7100102
  - libcxx=21.1.7=hf598326_0
  - libcxx-devel=19.1.7=h6dc3340_2
  - libcxx-headers=19.1.7=h707e725_2
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libfabric=2.3.1=hce30654_1
  - libfabric1=2.3.1=hc919400_1
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.86.3=hfe11c1f_0
  - libhwloc=2.12.1=default_ha3cc4f2_1003
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - libklu=2.3.5=h4370aa4_7100102
  - liblapack=3.11.0=4_hd9741b5_openblas
  - libldl=3.3.2=h99b4a89_7100102
  - libllvm19=19.1.7=h8e0c9ce_2
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libparu=1.0.0=h317a14d_7100102
  - libpng=1.6.53=hfab5511_0
  - libptscotch=7.0.10=int32_hf99fa1b_2
  - librbio=4.3.4=h99b4a89_7100102
  - libscotch=7.0.10=int32_hed6a4d5_2
  - libsodium=1.0.20=h99b78c6_0
  - libspex=3.2.3=h15d103f_7100102
  - libspqr=4.3.4=h775d698_7100102
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libsuitesparseconfig=7.10.1=h4a8fc20_7100102
  - libtiff=4.7.1=h4030677_1
  - libumfpack=6.3.5=h7c2c975_7100102
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.7=h4a912ad_0
  - llvm-tools=19.1.7=h855ad52_2
  - llvm-tools-19=19.1.7=h91fd4e7_2
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - metis=5.1.0=h15f6cfe_1007
  - mistune=3.1.4=pyhcf101f3_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpi=1.0.1=mpich
  - mpi4py=4.1.1=py311h3f6cb2c_102
  - mpich=4.3.2=hf5485c1_101
  - mpmath=1.3.0=pyhd8ed1ab_1
  - mumps-include=5.8.1=ha6078a4_4
  - mumps-mpi=5.8.1=h3d714e2_4
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.5.0=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parmetis=4.0.3=ha4b917a_1007
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.47=h30297fc_0
  - petsc=3.24.2=real_hffff12d_0
  - petsc4py=3.24.2=np2py310h5a689d9_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - pkg-config=0.29.2=hde07d2e_1009
  - pkgconfig=1.5.5=pyhd8ed1ab_5
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.1.3=py311h5bb9006_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=12.1=py311hce6e4fa_0
  - pyobjc-framework-cocoa=12.1=py311h9049b8e_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.11.14=hd8ed1ab_2
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py311h13abfa4_0
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py311h71babbd_0
  - scalapack=2.2.0=h71a4f75_4
  - sdkroot_env_osx-arm64=14.5=hfa17104_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - sigtool=0.1.3=h44b9a77_0
  - six=1.17.0=pyhe01879c_1
  - slepc=3.24.1=real_hfff4912_0
  - slepc4py=3.24.1=np2py310ha76e2c4_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - suitesparse=7.10.1=h3071b36_7100102
  - superlu=7.0.0=h742a510_1
  - superlu_dist=9.1.0=h89afcdd_0
  - sympy=1.14.0=pyh2585a3b_105
  - tapi=1600.0.11.8=h997e182_0
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h892fb3f_3
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.3=py311h9408147_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h8577fbf_1
  - unicodedata2=17.0.0=py311h9408147_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.1=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.2=h248ca61_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - anytree==2.13.0
      - cmake==4.0.3
      - contourpy==1.3.0
      - derivative==0.6.3
      - fonttools==4.58.5
      - gsw==3.6.19
      - hydra-core==1.3.2
      - joblib==1.5.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - numpy==2.0.2
      - omegaconf==2.3.0
      - ordered-set==4.1.0
      - pandas==2.3.1
      - pillow==11.3.0
      - pyparsing==3.2.3
      - pysindy==1.7.5
      - pyyaml==6.0.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - scs==3.2.7.post2
      - seaborn==0.13.2
      - threadpoolctl==3.6.0
      - xarray==2024.7.0
prefix: /Users/oscar/miniconda3/envs/pix
